import { app, BrowserWindow, dialog, ipcMain, Menu } from 'electron';
import { writeFile } from 'node:fs/promises';
import dotenv from 'dotenv';
import {
  fetchNewInvoicesBySupplier,
  getDocuments,
  getDocument,
  downloadDocumentAttachment,
  markDocumentItemsPrinted,
} from './services/mail/mailService';
import {
  getDefaultPrinter,
  setDefaultPrinter,
  getTagType,
  setTagType,
  hasImapPassword,
  setImapPassword,
  hasEmail,
  setEmail,
  hasDatabaseUrl,
  setDatabaseUrl,
  hasYandexFolderId,
  setYandexFolderId,
  hasYandexApiKey,
  setYandexApiKey,
} from './services/config/configService';
import { resetPrismaClient } from './services/db/prisma';
import { getPrinterList, printTags } from './services/printer/printerService';
import {
  checkForUpdates,
  getAppVersion,
  getUpdateStatus,
  initAutoUpdater,
  quitAndInstall,
} from './services/update/updateService';
import { TagType } from './services/printer/constants';
import { TagData } from './services/printer/types';
import { GetDocumentItemsParams, SupplierId } from './shared/types';
import { getDocumentItems } from './services/documentItems/documentItemsService';
import appIcon from './assets/rascenka-icon.png';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

dotenv.config();

ipcMain.handle(
  'mail:fetch-new-invoices-by-supplier',
  async (_, supplierId: SupplierId) => {
    return fetchNewInvoicesBySupplier(supplierId);
  },
);
ipcMain.handle(
  'mail:get-documents',
  async (_, supplierIds?: SupplierId | SupplierId[]) => {
    return getDocuments(supplierIds);
  },
);
ipcMain.handle(
  'mail:get-document',
  async (_, supplierId: SupplierId, documentId: string) => {
    return getDocument(supplierId, documentId);
  },
);
ipcMain.handle(
  'mail:download-document',
  async (event, supplierId: SupplierId, documentId: string) => {
    const { buffer, filename } = await downloadDocumentAttachment(
      supplierId,
      documentId,
    );
    const window = BrowserWindow.fromWebContents(event.sender);
    const result = await dialog.showSaveDialog(window ?? undefined, {
      defaultPath: filename,
    });

    if (result.canceled || !result.filePath) {
      return { saved: false };
    }

    await writeFile(result.filePath, buffer);
    return { saved: true, filePath: result.filePath };
  },
);
ipcMain.handle(
  'documentItems:get-document-items',
  async (_, params: GetDocumentItemsParams) => {
    return getDocumentItems(params);
  },
);
ipcMain.handle('printer:get-printer-list', async () => {
  return getPrinterList();
});
ipcMain.handle(
  'printer:print-tags',
  async (
    _: unknown,
    data: TagData<TagType>[],
    printerName?: string,
  ) => {
    await printTags(data, printerName);

    const itemIds = [
      ...new Set(
        data
          .map((item) => Number(item.number))
          .filter((id) => Number.isInteger(id) && id > 0),
      ),
    ];

    await markDocumentItemsPrinted(itemIds);
  },
);
ipcMain.handle('config:get-default-printer', () => {
  return getDefaultPrinter();
});
ipcMain.handle(
  'config:set-default-printer',
  (_: unknown, printerName: string | null) => {
    setDefaultPrinter(printerName);
  },
);
ipcMain.handle('config:get-tag-type', () => {
  return getTagType();
});
ipcMain.handle('config:set-tag-type', (_: unknown, tagType: TagType) => {
  setTagType(tagType);
});
ipcMain.handle('config:has-imap-password', () => {
  return hasImapPassword();
});
ipcMain.handle('config:set-imap-password', (_: unknown, password: string) => {
  setImapPassword(password);
});
ipcMain.handle('config:has-email', () => {
  return hasEmail();
});
ipcMain.handle('config:set-email', (_: unknown, email: string) => {
  setEmail(email);
});
ipcMain.handle('config:has-database-url', () => {
  return hasDatabaseUrl();
});
ipcMain.handle('config:set-database-url', (_: unknown, databaseUrl: string) => {
  setDatabaseUrl(databaseUrl);
  resetPrismaClient();
});
ipcMain.handle('config:has-yandex-folder-id', () => {
  return hasYandexFolderId();
});
ipcMain.handle(
  'config:set-yandex-folder-id',
  (_: unknown, folderId: string) => {
    setYandexFolderId(folderId);
  },
);
ipcMain.handle('config:has-yandex-api-key', () => {
  return hasYandexApiKey();
});
ipcMain.handle('config:set-yandex-api-key', (_: unknown, apiKey: string) => {
  setYandexApiKey(apiKey);
});
ipcMain.handle('update:get-version', () => {
  return getAppVersion();
});
ipcMain.handle('update:get-status', () => {
  return getUpdateStatus();
});
ipcMain.handle('update:check', () => {
  checkForUpdates();
});
ipcMain.handle('update:quit-and-install', () => {
  quitAndInstall();
});
ipcMain.handle('window:minimize', (event) => {
  BrowserWindow.fromWebContents(event.sender)?.minimize();
});
ipcMain.handle('window:maximize', (event) => {
  const window = BrowserWindow.fromWebContents(event.sender);
  if (!window) return;
  if (window.isMaximized()) {
    window.unmaximize();
    return;
  }
  window.maximize();
});
ipcMain.handle('window:close', (event) => {
  BrowserWindow.fromWebContents(event.sender)?.close();
});
ipcMain.handle('window:is-maximized', (event) => {
  return BrowserWindow.fromWebContents(event.sender)?.isMaximized() ?? false;
});

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1200,
    width: 1600,
    frame: false,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
    icon: appIcon,
  });

  const sendMaximizedChanged = () => {
    mainWindow.webContents.send(
      'window:maximized-changed',
      mainWindow.isMaximized(),
    );
  };
  mainWindow.on('maximize', sendMaximizedChanged);
  mainWindow.on('unmaximize', sendMaximizedChanged);

  // Menu.setApplicationMenu(null) removes default accelerators (Ctrl+Shift+I, F12).
  mainWindow.webContents.on('before-input-event', (event, input) => {
    const isDevToolsShortcut =
      input.key === 'F12' ||
      (input.control && input.shift && input.key.toLowerCase() === 'i');
    if (!isDevToolsShortcut || input.type !== 'keyDown') return;
    event.preventDefault();
    mainWindow.webContents.toggleDevTools();
  });

  mainWindow.maximize();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', () => {
  initAutoUpdater();
  createWindow();
});

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.

Menu.setApplicationMenu(null);
