import { app, BrowserWindow, ipcMain } from 'electron';
import dotenv from 'dotenv';
import {
  fetchNewInvoicesBySupplier,
  getSupplierDocuments,
  getDocument,
} from './services/mail/mailService';
import { getPrinterList, printTags } from './services/printer/printerService';
import { TagType } from './services/printer/constants';
import { TagData } from './services/printer/types';
import { SupplierId } from './shared/types';

// This allows TypeScript to pick up the magic constants that's auto-generated by Forge's Webpack
// plugin that tells the Electron app where to look for the Webpack-bundled app code (depending on
// whether you're running in development or production).
declare const MAIN_WINDOW_WEBPACK_ENTRY: string;
declare const MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY: string;

dotenv.config();

ipcMain.handle(
  'mail:fetch-new-invoices-by-supplier',
  async (_, supplierId: SupplierId) => {
    return fetchNewInvoicesBySupplier(supplierId);
  },
);
ipcMain.handle(
  'mail:get-supplier-documents',
  async (_, supplierId: SupplierId) => {
    return getSupplierDocuments(supplierId);
  },
);
ipcMain.handle(
  'mail:get-document',
  async (_, supplierId: SupplierId, documentId: string) => {
    return getDocument(supplierId, documentId);
  },
);
ipcMain.handle('printer:get-printer-list', async () => {
  return getPrinterList();
});
ipcMain.handle(
  'printer:print-tags',
  async <T extends TagType>(
    _: unknown,
    tagType: T,
    data: TagData<T>[],
    printerName?: string,
  ) => {
    return printTags(tagType, data, printerName);
  },
);

// Handle creating/removing shortcuts on Windows when installing/uninstalling.
if (require('electron-squirrel-startup')) {
  app.quit();
}

const createWindow = (): void => {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    height: 1200,
    width: 1600,
    webPreferences: {
      preload: MAIN_WINDOW_PRELOAD_WEBPACK_ENTRY,
    },
  });

  mainWindow.maximize();

  // and load the index.html of the app.
  mainWindow.loadURL(MAIN_WINDOW_WEBPACK_ENTRY);

  // Open the DevTools.
  mainWindow.webContents.openDevTools();
};

// This method will be called when Electron has finished
// initialization and is ready to create browser windows.
// Some APIs can only be used after this event occurs.
app.on('ready', createWindow);

// Quit when all windows are closed, except on macOS. There, it's common
// for applications and their menu bar to stay active until the user quits
// explicitly with Cmd + Q.
app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit();
  }
});

app.on('activate', () => {
  // On OS X it's common to re-create a window in the app when the
  // dock icon is clicked and there are no other windows open.
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow();
  }
});

// In this file you can include the rest of your app's specific main process
// code. You can also put them in separate files and import them here.
